#include "led.h"

void led_init(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
	
	GPIOE->MODER |= (GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0 | GPIO_MODER_MODER10_0 | GPIO_MODER_MODER11_0 | GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
	GPIOE->MODER &= ~(GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1 | GPIO_MODER_MODER12_1 | GPIO_MODER_MODER13_1 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER15_1);
	GPIOE->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR8 | GPIO_OSPEEDER_OSPEEDR9 | GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR11 | GPIO_OSPEEDER_OSPEEDR12 | GPIO_OSPEEDER_OSPEEDR13 | GPIO_OSPEEDER_OSPEEDR14 | GPIO_OSPEEDER_OSPEEDR15);
}

void led_blink(void)
{
	int i = 0;
	GPIOE->BSRR |= (GPIO_BSRR_BS_8|GPIO_BSRR_BS_9|GPIO_BSRR_BS_10|GPIO_BSRR_BS_11|GPIO_BSRR_BS_12|GPIO_BSRR_BS_13|GPIO_BSRR_BS_14|GPIO_BSRR_BS_15);
	for(i = 0; i < 1000000; i++);
	GPIOE->BSRR |= (GPIO_BSRR_BR_8|GPIO_BSRR_BR_9|GPIO_BSRR_BR_10|GPIO_BSRR_BR_11|GPIO_BSRR_BR_12|GPIO_BSRR_BR_13|GPIO_BSRR_BR_14|GPIO_BSRR_BR_15);
	for(i = 0; i < 1000000; i++);
}
